# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-26 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='0이상의 숫자를 입력해주세요.', null=True, unique=True, verbose_name='회원번호')),
                ('stname', models.CharField(help_text='최대 10자까지 입력가능', max_length=10, null=True, verbose_name='회원이름')),
                ('prtname', models.CharField(help_text='최대 10자까지 입력가능', max_length=10, null=True, verbose_name='보호자 성함')),
                ('contact', models.CharField(help_text='010XXXXXXXX', max_length=11, null=True, verbose_name='보호자 연락처')),
                ('address', models.CharField(help_text='00시 000로 건물번호 세부주소', max_length=100, null=True, verbose_name='주소')),
                ('dateOfBirth', models.DateField(help_text='YYYY-MM-DD', verbose_name='생년월일')),
                ('dateOfEnroll', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='가입일')),
                ('actState', models.CharField(choices=[('HUMAN', '휴먼'), ('ACTIVE', '활성화')], default='ACTIVE', max_length=6, null=True, verbose_name='회원상태')),
                ('isPayday', models.CharField(choices=[('PAY', '결제일'), ('PAYED', '비결제일')], default='PAYED', max_length=10, null=True, verbose_name='결제일 여부')),
                ('gender', models.CharField(choices=[('M', '남'), ('F', '여')], max_length=2, null=True, verbose_name='성별')),
                ('school', models.CharField(help_text='XXX중학교', max_length=20, null=True, verbose_name='학교')),
                ('years', models.CharField(blank=True, max_length=4, null=True, verbose_name='학년')),
                ('sheet', models.CharField(blank=True, default='main', max_length=10, null=True, verbose_name='현재시트명')),
                ('filepath', models.CharField(blank=True, max_length=50, null=True, verbose_name='차트파일 위치')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.Lesson', verbose_name='수업')),
            ],
        ),
    ]
