# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-27 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False, verbose_name='Merchant Code')),
                ('item', models.CharField(default='', help_text='최대 20자까지 입력가능', max_length=10, unique=True, verbose_name='수업')),
                ('price', models.IntegerField(default=0, help_text='숫자만 입력하세요.', verbose_name='가격')),
                ('teacher', models.CharField(default='', help_text='강사명', max_length=10, null=True, verbose_name='강사')),
                ('days', models.CharField(default='', help_text='예시: 월/목', max_length=10, null=True, verbose_name='수업요일')),
                ('people', models.IntegerField(blank=True, default=0, null=True, verbose_name='수강생 수')),
            ],
        ),
    ]
