# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-27 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False, verbose_name='번호')),
                ('attendanceDate', models.DateField(null=True, verbose_name='출석날짜')),
                ('fillOut', models.CharField(choices=[('작성', '작성'), ('미작성', '미작성')], default='미작성', max_length=6, null=True, verbose_name='차트작성여부')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
        ),
    ]
